ServersideGameNight/Controllers/BoardGameController.cs
using Avans.GameNight.App.Models;
using Avans.GameNight.Core.Domain.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Avans.GameNight.Core.DomainServices.Interfaces;
using Microsoft.AspNetCore.Identity;
using Avans.GameNight.Core.Domain.Models;

namespace Avans.GameNight.App.Controllers
{
    public class BoardGameController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IBoardGameRepository _boardGameRepo;
        private readonly IPlayerRepository _playerRepo;

        public BoardGameController(UserManager<IdentityUser> userManager, IBoardGameRepository boardGameRepo, IPlayerRepository playerRepo)
        {
            _userManager = userManager;
            _boardGameRepo = boardGameRepo;
            _playerRepo = playerRepo;

        }

        public ActionResult AccesDenied()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var boardGames = await _boardGameRepo.GetBoardGames();
            
            


            return View(boardGames); 
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string nameGame)
        {
           
            var boardGame = await _boardGameRepo.GetBoardGameByName(nameGame);
            return View(boardGame);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit(BoardGame BoardGameTemp)
        {
           
            if (ModelState.IsValid)
            {
                await _boardGameRepo.UpdateBoardGame(BoardGameTemp);
            }
            return RedirectToAction("Index");

        }


        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var user = await _userManager.GetUserAsync(User);
            var player = await _playerRepo.GetPlayerByMailAdress(user.Email);

            if (player.role == Role.HOST)
            {

                return View();
            }
            else
            {
                return RedirectToAction("AccesDenied");
            }

        }
        [HttpPost]
        public async Task<IActionResult> Create(BoardGame boardGame)
        {
            try
            {
                var image = Request.Form.Files[0];

                var temp = new BoardGame
                {
                    NameGame = boardGame.NameGame,
                    Genre = boardGame.Genre,
                    Desciption = boardGame.Desciption,  
                    Mature = boardGame.Mature,  
                    KindOfGame = boardGame.KindOfGame,
                    PictureFormat = image.ContentType,

              
                };
               
                var memoryStream = new MemoryStream();
                image.CopyTo(memoryStream);
                temp.PictureB = memoryStream.ToArray();

                //if (ModelState.IsValid)
                //{
                   

                    await _boardGameRepo.AddBoardGame(temp);
                //}
                TempData["SuccessMessage"] = "Successfully Created: "+temp.NameGame;
                return RedirectToAction("Index");


            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Forum is not correct";
                return RedirectToAction("Create");
            }


        }

        // POST: PatientController/Delete/5
        [HttpPost]
       
        public async Task<IActionResult> Delete(string name)
        {
            //GetPatientById can throw an error about id not higher than 0
            try
            {
                var game = await _boardGameRepo.GetBoardGameByName(name);

                if (game == null)
                {
                    return NotFound("The BoardGame requested to delete has not been found.");
                }
                await _boardGameRepo.DestroyBoardGame(game);
                TempData["SuccessMessage"] = "Successfully Deleted: " + name;
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "User not found";
                return RedirectToAction("Index");
            }
        }
    }
}

ServersideGameNight/Controllers/BoardGameNightController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Avans.GameNight.Core.Domain.Interfaces;
using Avans.GameNight.Core.Domain.Models;
using Avans.GameNight.Core.DomainServices.Interfaces;

namespace Avans.GameNight.App.Controllers
{
    public class BoardGameNightController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IBoardGameNightPlayerRepository _boardGameNightPlayerRepo;
        private readonly IPlayerRepository _playerRepo;
        private IBoardGameNightService _boardgameNightService;


        public BoardGameNightController(UserManager<
            IdentityUser> userManager, IPlayerRepository playerRepo, IBoardGameNightPlayerRepository boardGameNightPlayerRepo,
            IBoardGameNightService boardgamenightService)
        {
            _userManager = userManager;
            _boardGameNightPlayerRepo = boardGameNightPlayerRepo;
            _playerRepo = playerRepo;
            _boardgameNightService = boardgamenightService;

        }


        // GET: BoardGameNightController
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var boardGameNights = await _boardgameNightService.GetBoardGameNights();
            return View(boardGameNights);
        }
        //GET MyBoardGames
        [HttpGet]
        public async Task<IActionResult> MyBoardGameNights()
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var myBoardGames = await _boardgameNightService.GetBoardGameNightsByHost(user.Email);

                return View(myBoardGames);
            }

            catch (ArgumentException)
            {
                return this.NotFound("The user is not found.");
            }
        }

        public ActionResult AccesDenied()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> AddBoardGame([FromQuery] string nameNight)
        {
            var boardGameNight = await _boardgameNightService.GetBoardGameNightByName(nameNight);
            var boardGames = await _boardgameNightService.GetBoardGameNightBoardGames();
            ViewBag.BoardGames = boardGames;
            ViewBag.NameNightBag = boardGameNight.NameNight;
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> AddBoardGame([FromQuery] string nameNight,
            BoardGameNightBoardGame boardGameNightBoardGame)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var BoardGameNight = await _boardgameNightService.GetBoardGameNightByName(nameNight);
                var boardGames = await _boardgameNightService.GetBoardGameNightBoardGames();

                ViewBag.BoardGames = boardGames;


                if (user.Email != BoardGameNight.Host)
                {
                    throw new Exception("Youre not the Owner!");
                }

                var newBoardGame = new BoardGameNightBoardGame()
                {
                    BoardGameNameGame = boardGameNightBoardGame.BoardGameNameGame,
                    BoardGameNightNameNight = BoardGameNight.NameNight,
                };

                var oldBoardGame =
                    await _boardgameNightService.GetBoardGameByName(newBoardGame.BoardGameNameGame);

                var boardGameExists = oldBoardGame.FirstOrDefault(bgnp => bgnp.BoardGameNightNameNight == nameNight);
                if (boardGameExists != null)
                {
                    throw new Exception("BoardGame already added");
                }


                if (BoardGameNight.BoardGameNightBoardGame == null ||
                    !BoardGameNight.BoardGameNightBoardGame.Contains(newBoardGame))
                {
                    BoardGameNight.BoardGameNightBoardGame?.Add(newBoardGame);
                    await _boardgameNightService.UpdateBoardGameNightByBoardGameNight(BoardGameNight);
                    await _boardgameNightService.AddGameNightBoardGame(newBoardGame);
                }

                TempData["SuccessMessage"] = "Successfully Added: " + newBoardGame.BoardGameNameGame;
                return RedirectToAction("MyBoardGameNights");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Error " + ex.Message;
                return RedirectToAction("MyBoardGameNights");
            }
        }

        //JOIN: 
        [HttpPost]
        public async Task<IActionResult> Join(string nameNight)
        {

            try
            {
                var user = await _userManager.GetUserAsync(User);
                var player1 = await _playerRepo.GetPlayerByMailAdress(user.Email);
                var gameNight = await _boardgameNightService.GetBoardGameNightByName(nameNight);
                var oldPlayer = await _boardGameNightPlayerRepo.GetBoardGameNightPlayersByName(user.Email);


                if (player1 == null)
                {
                    throw new Exception("Player is null");
                }

                if (user.Email == gameNight.Host)
                {
                    throw new Exception("Cannot join own GameNight");
                }


                var playerExists = oldPlayer.FirstOrDefault(bgnp => bgnp.BoardGameNightNameNight == nameNight);
                if (playerExists != null)
                {
                    throw new Exception("Youre already in this GameNight");
                }

                if (ModelState.IsValid)
                {
                    if (gameNight.TotalPlayers + 1 > gameNight.MaxPlayers)
                    {
                        throw new Exception("GameNight is full");
                    }

                    gameNight.TotalPlayers = gameNight.TotalPlayers + 1;

                    //BoardGameNightPlayer maken
                    var newPlayer = new BoardGameNightPlayer()
                    {
                        PlayerMailAddress = user.Email,
                        BoardGameNightNameNight = gameNight.NameNight,
                    };


                    if (gameNight.BoardGameNightPlayer.Contains(newPlayer))
                    {
                        throw new Exception("Already in this gamenight");
                    }

                    if ((gameNight.BoardGameNightPlayer == null) || !gameNight.BoardGameNightPlayer.Contains(newPlayer))
                    {
                        gameNight.BoardGameNightPlayer?.Add(newPlayer);
                        await _boardgameNightService.UpdateBoardGameNightByBoardGameNight(gameNight);
                        await _boardGameNightPlayerRepo.AddBoardGameNightPlayer(newPlayer);
                    }
                }

                TempData["SuccessMessage"] = "Successfully joined: " + gameNight.NameNight;
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;

                return RedirectToAction("Index");
            }
        }

        //Leave: 
        [HttpPost]
        public async Task<IActionResult> Leave(string nameNight)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var gameNight = await _boardgameNightService.GetBoardGameNightByName(nameNight);
                var oldPlayer = await _boardGameNightPlayerRepo.GetBoardGameNightPlayersByName(user.Email);

                if (user.Email == gameNight.Host)
                {
                    throw new Exception("Cannot leave your own gamenight");
                }


                if (ModelState.IsValid)
                {
                    if (gameNight.TotalPlayers - 1 < 0)
                    {
                        throw new Exception("GameNight cannot be empty");
                    }

                    var playerExists = oldPlayer.FirstOrDefault(bgnp => bgnp.BoardGameNightNameNight == nameNight);
                    if (playerExists != null)
                    {
                        gameNight.TotalPlayers = gameNight.TotalPlayers - 1;

                        await _boardgameNightService.UpdateBoardGameNightByBoardGameNight(gameNight);
                        await _boardGameNightPlayerRepo.DestroyBoardGameNightPlayer(playerExists);
                    }

                    await _boardgameNightService.UpdateBoardGameNightByBoardGameNight(gameNight);
                }


                TempData["SuccessMessage"] = "Successfully leaved: " + gameNight.NameNight;
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var user = await _userManager.GetUserAsync(User);
            var player = await _playerRepo.GetPlayerByMailAdress(user.Email);
            var BoardGames = await _boardgameNightService.GetBoardGameNightBoardGames();

            ViewBag.BoardGamesList = BoardGames;

            if (player.role == Role.HOST)
            {
                return View();
            }
            else
            {
                return RedirectToAction("AccesDenied");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create(BoardGameNight boardGameNight)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                boardGameNight.Host = user.Email;
                boardGameNight.TotalPlayers = 1;

                //boardGameNight.BoardGameNightBoardGame = ViewBag.BoardGamesList;
                await _boardgameNightService.AddBoardGameNight(boardGameNight);
                

ServersideGameNight/Controllers/PlayerController.cs
using Avans.GameNight.Core.DomainServices.Interfaces;
using Avans.GameNight.App.Models;
using Avans.GameNight.Core.Domain.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Avans.GameNight.Core.Domain.Models;

namespace Avans.GameNight.App.Controllers
{
    public class PlayerController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IPlayerRepository _playerRepo;

        public PlayerController(UserManager<IdentityUser> userManager, IPlayerRepository playerRepo)
        {
            _userManager = userManager;
            _playerRepo = playerRepo;

        }
        [HttpGet]
        public async Task<IActionResult> Index()

        {
            var players = await _playerRepo.GetPlayers();
            // ViewBag.test = players;


            return View(players);
        }
        [HttpGet]
        public async Task<IActionResult> Profile()

        {

            try
            {
                var user = await _userManager.GetUserAsync(User);
                var player = await _playerRepo.GetPlayerByMailAdress(user.Email);



                return this.View(player);
            }
            catch (ArgumentException)
            {
                return this.NotFound("The user is not found.");
            }

        }
        public async Task<IActionResult> Edit()
        {
            var user = await _userManager.GetUserAsync(User);
            var player = await _playerRepo.GetPlayerByMailAdress(user.Email);
            return View(player);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit(Player playerTemp)
        {
            if (playerTemp.Adress == null)
            {
                playerTemp.Adress = "";
            }
            if (playerTemp.FoodPreference == null)
            {
                playerTemp.FoodPreference = "";
            }
            if (playerTemp.DrinkPreference == null)
            {
                playerTemp.DrinkPreference = "";
            }
            if (playerTemp.City == null)
            {
                playerTemp.City = "";
            }
            //if (ModelState.IsValid)
            //{
            await _playerRepo.UpdatePlayer(playerTemp);
            //}

            TempData["SuccessMessage"] = "Succes Edit! "+playerTemp.MailAddress;
            return RedirectToAction("Profile", new { MailAdress = playerTemp.MailAddress });

        }
    }
}

ServersideGameNight/Views/Shared/_Layout.cshtml
@using Avans.GameNight.Core.DomainServices.Interfaces
@using Microsoft.AspNetCore.Identity
@using Avans.GameNight.Core.Domain.Interfaces
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@inject IPlayerRepository _playerRepo
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ServersideGameNight</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ServersideGameNight.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <!-- Sidebar -->
            <nav class="col-md-2 d-none d-md-block bg-dark sidebar" style="height: 100vh; max-width: 10.666667%;">
                <div class="sidebar-sticky">
                    <!-- Sidebar navigation -->
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="LoginIndex"> <img src="~/img//BoardgameLogo.png" width="145" height="110" alt="Logo" /></a>
                        </li>
                    </ul>

                    <ul class="nav flex-column">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white bigger-nav-item" asp-area="" asp-controller="BoardGameNight" asp-action="Create">
                                    <i class="fas fa-plus"></i> Create Game
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-white bigger-nav-item" asp-area="" asp-controller="BoardGameNight" asp-action="Index">
                                    <i class="fas fa-sign-in-alt"></i> Join Game
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-white bigger-nav-item" asp-area="" asp-controller="BoardGame" asp-action="Index">
                                    <i class="fas fa-chess-board"></i> Boardgames
                                </a>
                            </li>
                        }
                        else
                        {

                            <li class="nav-item">
                                <a class="nav-link text-white bigger-nav-item" asp-area="" asp-controller="Account" asp-action="Login">
                                    <i class="fas fa-sign-in-alt"></i> Login
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-white navbar-text navbar-right  bigger-nav-item" asp-area="" asp-controller="Account" asp-action="Register">
                                    <i class="fas fa-user-plus"></i> Register
                                </a>
                            </li>
                        }

                    </ul>


                    <ul class="nav flex-column mt-4">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white bigger-nav-item" asp-area="" asp-controller="BoardGameNight" asp-action="MyBoardGameNights">
                                    <i class="fas fa-gamepad"></i> My Games
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-white bigger-nav-item" asp-area="" asp-controller="Player" asp-action="Profile">
                                    <i class="fas fa-user"></i> Profile
                                </a>
                            </li>

                            <li class="nav-item">
                                <form id="logoutForm" class="form-inline" asp-controller="Account" asp-action="Logout">
                                    <button id="logout" type="submit" class="nav-link btn btn-link text-white  bigger-nav-item">
                                        <i class="fas fa-sign-out-alt"></i> Logout
                                    </button>
                                </form>
                            </li>

                        }
                    </ul>
                </div>
            </nav>

            <!-- Main content -->
            <main role="main" class="col-md-10 ml-sm-auto col-lg-10 px-4">
                <div class="container">
                    <!-- Your existing content goes here -->
                    @if (TempData["SuccessMessage"] != null)
                    {
                        <div class="alert alert-success" role="alert">
                            <strong>@TempData["SuccessMessage"]</strong>
                        </div>
                    }
                    @if (TempData["WarningMessage"] != null)
                    {
                        <div class="alert alert-warning" role="alert">
                            <strong>@TempData["WarningMessage"]</strong>
                        </div>
                    }
                    @if (TempData["ErrorMessage"] != null)
                    {
                        <div class="alert alert-danger" role="alert">
                            <strong>@TempData["ErrorMessage"]</strong>
                        </div>
                    }
                    @RenderBody()
                </div>
            </main>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>